name: Build

on:
  push:
    branches: [ master ]
  pull_request: 

env:
  # Disable the .NET logo in the console output.
  #DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  #DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  #DOTNET_CLI_TELEMETRY_OPTOUT: true

  BUILD_ARTIFACT_PATH: ${{github.workspace}}/build-artifacts

jobs:
  build:
    name: Build ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Configure Windows
      if: matrix.os == 'windows-latest'
      run: choco install Memurai-Developer
    - name: Configure Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo systemctl start mongod && sudo apt-get install redis-server
    - name: Configure MacOS
      if: matrix.os == 'macOS-latest'
      run: brew services start mongodb-community && brew install redis && brew services start redis

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test with Coverage
      run: dotnet test --no-restore --logger trx --results-directory ${{env.BUILD_ARTIFACT_PATH}}/coverage --collect "XPlat Code Coverage" --settings CodeCoverage.runsettings /p:SkipBuildVersioning=true
    - name: Pack
      run: dotnet pack --no-build -c Release /p:PackageOutputPath=${{env.BUILD_ARTIFACT_PATH}}
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.os}}
        path: ${{env.BUILD_ARTIFACT_PATH}}

  coverage:
    name: Process code coverage
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download coverage reports
      uses: actions/download-artifact@v2
    - name: Install ReportGenerator tool
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    - name: Prepare coverage reports
      run: reportgenerator -reports:*/coverage/*/coverage.cobertura.xml -targetdir:./ -reporttypes:Cobertura
    - name: Upload coverage report
      uses: codecov/codecov-action@v1.0.13
      with:
        file: Cobertura.xml
        fail_ci_if_error: false
    - name: Save combined coverage report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: Cobertura.xml
